import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@/components/Convex";
import { Toaster } from "@/components/ui/toaster";

const notosans = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={notosans.className}>
        <ConvexClientProvider>
          {children} <Toaster />
        </ConvexClientProvider>
      </body>
    </html>
  );
}
